apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: platform-flags
  namespace: default
spec:
  flagSpec:
    flags:
      fast-delivery:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
